title: Kafka Cheat Sheet
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://mccullya.github.io.github.io/kafka-cheat-sheet

aux_links:
  Template Repository: https://github.com/mccullya/kafka-cheat-sheet
